# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
#
# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jackson & Son's Property Management
name: Jackson & Son's Property Management LLC
logo: "/assets/images/JS_Logo_Green_mini_bevel.png"
description: >- # this means to ignore newlines until "baseurl:"
  Jackson & Son's Property Management provides property management services for mowing, landscaping & landscape design, excavation
  irrigation, and hardscaping in Clark, Champaign, and Montgomery counties in Ohio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jacksonspropmanagement.com" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]
facebook_url: https://www.facebook.com/Jacksonsonspropertymanagement
instagram_url: https://www.instagram.com/jacksonsonspropertymanagement/
phone_number: (937) 631-6548

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-234783122-1"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "default", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
